In [1]:
# To support both python 2 and python 3
# 让这份笔记同步支持 python 2 和 python 3
from __future__ import division
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib
%matplotlib inline

**8. In Section 10.2.3, a formula for calculating PVE was given in Equa-
tion 10.8. We also saw that the PVE can be obtained using the sdev
output of the prcomp() function.
On the USArrests data, calculate PVE in two ways:
(a) Using the sdev output of the prcomp() function, as was done in
Section 10.2.3.
(b) By applying Equation 10.8 directly. That is, use the prcomp()
function to compute the principal component loadings. Then,
use those loadings in Equation 10.8 to obtain the PVE.
These two approaches should give the same results.
Hint: You will only obtain the same results in (a) and (b) if the same
data is used in both cases. For instance, if in (a) you performed
prcomp() using centered and scaled variables, then you must center
and scale the variables before applying Equation 10.3 in (b).**

In [2]:
USArrests = pd.read_csv('Data/USArrests.csv', na_values='?').dropna()

In [3]:
USArrests.head()

State  Murder  Assault  UrbanPop  Rape
0     Alabama    13.2      236        58  21.2
1      Alaska    10.0      263        48  44.5
2     Arizona     8.1      294        80  31.0
3    Arkansas     8.8      190        50  19.5
4  California     9.0      276        91  40.6

In [4]:
from sklearn.preprocessing import scale
from sklearn.decomposition import PCA
XSC = scale(USArrests[['Murder','Assault','UrbanPop','Rape']],axis = 0)
pca = PCA()
pca.fit(XSC)

PCA(copy=True, iterated_power='auto', n_components=None, random_state=None,
    svd_solver='auto', tol=0.0, whiten=False)

**(a) Using the sdev output of the prcomp() function, as was done in Section 10.2.3.**

In [5]:
pca.explained_variance_ / pca.explained_variance_.sum()

array([0.62006039, 0.24744129, 0.0891408 , 0.04335752])

**(b) By applying Equation 10.8 directly. That is, use the prcomp()
function to compute the principal component loadings. Then,
use those loadings in Equation 10.8 to obtain the PVE.**

In [6]:
test = XSC.dot(pca.components_.T)
((test ** 2).sum(axis = 0))/((XSC ** 2).sum())

array([0.62006039, 0.24744129, 0.0891408 , 0.04335752])

In [7]:
test2 = pca.transform(XSC)
((test2 ** 2).sum(axis = 0))/((XSC ** 2).sum())

array([0.62006039, 0.24744129, 0.0891408 , 0.04335752])